name: Create Cluster

on: pull_request

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
      - name: Checkout
        uses: actions/checkout@v2
      - name: Helm & Helmfile Action
        uses: hiberbee/github-action-helm@1.9.1
        with:
          helmfile: apply
          plugins: diff
      - name: Setup just
        uses: extractions/setup-just@v1
      - name: Install policies
        run: |
          just install-policies
      - name: Randomly try to install deployments
        run: |
          kubectl apply -f tests/invalid/deployment-without-labels.yaml
      - name: Run tests
        run: |
          just test
