name: Create Cluster

on: pull_request

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
      - name: Checkout
        uses: actions/checkout@v2
      - name: Helm & Helmfile Action
        uses: hiberbee/github-action-helm@1.9.1
        with:
          helmfile: apply
          plugins: diff
      # Kyverno is installed
      - name: Install policies
        run: |
          kubectl apply -f policies
      - name: Make sure invalid resources cannot be installed
        run: |
          let FAILED=0
          for f in tests/invalid/*.yaml; do
            if (kubectl apply -f $f 2>&1 > /dev/null); then
              echo "ERROR: $f should have been rejected"
              let FAILED=1
            fi

            kubectl delete -f $f --ignore-not-found 2>&1 > /dev/null
          done

          [[ $FAILED -ne 0 ]] && exit 1
      - name: Make sure valid resources can be installed
        run: |
          let FAILED=0
          for f in tests/valid/*.yaml; do
            if ! (kubectl apply -f $f 2>&1 > /dev/null); then
              echo "ERROR: $f should have been accepted"
              let FAILED=1
            fi

            kubectl delete -f $f --ignore-not-found 2>&1 > /dev/null
          done

          [[ $FAILED -ne 0 ]] && exit 1
